apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-rest-deployment
  ## WARNING: Para criar um pod dentro do namespace citado aqui, é necessário que o namespace já exista.
  namespace: namespace-teste
  labels:
    app: kube-rest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kube-rest
  template:
    metadata:
      labels:
        app: kube-rest
    spec:
      containers:
      - name: kube-rest
        image: api-kubernetes:latest
        ports:
        - containerPort: 80
