apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  ## WARNING: Para criar um pod dentro do namespace citado aqui, é necessário que o namespace já exista.
  namespace: namespace-teste
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
